spring.application.name=unifiedsecuritymaster
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/pms
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
logging.file.name=logs/app.log
logging.level.root=INFO
logging.level.com.example.splitease=DEBUG

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=500
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# ========== SPRING BATCH ==========
# Do NOT auto-run jobs at startup - we trigger manually / via scheduler
spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=always
spring.batch.jdbc.table-prefix=BATCH_

# ========== CSV VENDOR CONFIG ==========
securitymaster.csv.url-template=https://www.nseindia.com/api/historicalOR/generateSecurityWiseHistoricalData?from={from}&to={to}&symbol={symbol}&type=priceVolumeDeliverable&series={series}&csv=true
securitymaster.csv.base-url=https://www.nseindia.com
securitymaster.csv.default-series=EQ
#securitymaster.csv.lookback-days=1825
securitymaster.csv.initial-lookback-days=1825
securitymaster.csv.overlap-days=5
securitymaster.csv.skip-if-updated-within-hours=12
securitymaster.csv.storage-dir=./data/csv
securitymaster.csv.keep-files=true
securitymaster.csv.connect-timeout-ms=10000
securitymaster.csv.read-timeout-ms=60000
securitymaster.csv.insecure-ssl=true

#Mutual Funds Processing
securitymaster.mf.base-url=https://api.tigzig.com
securitymaster.mf.nav-path=/mf/v1/nav
securitymaster.mf.initial-since=2020-01-01
securitymaster.mf.overlap-days=5
securitymaster.mf.connect-timeout-ms=10000
securitymaster.mf.read-timeout-ms=120000
securitymaster.mf.insecure-ssl=true

# ========== COMMODITY SPOT (NSE) ==========
securitymaster.commodity.base-url=https://www.nseindia.com
securitymaster.commodity.url-template=https://www.nseindia.com/api/historical-spot-price?symbol={symbol}&fromDate={from}&toDate={to}
securitymaster.commodity.date-format=dd-MM-yyyy
securitymaster.commodity.initial-since=2025-09-25
securitymaster.commodity.overlap-days=5
# ========== BATCH TUNING ==========
securitymaster.batch.chunk-size=5
securitymaster.batch.page-size=20
securitymaster.batch.skip-limit=10
securitymaster.batch.retry-limit=3

# ========== SCHEDULER ==========
securitymaster.schedule.cron=0 30 18 * * MON-FRI
securitymaster.schedule.zone=Asia/Kolkata
